config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :posts, only: [:new, :create, :index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save :downcase_email
  before_create :create_remember_digest

  has_secure_password

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(string)
    Digest::SHA1.hexdigest string
  end


  def create_remember_digest
    self.remember_token  = User.new_token
    self.remember_digest = User.digest(remember_token.to_s)
  end

    private

    def downcase_email
      email.downcase!
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(user_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:success] = "Successfully created post!"
      redirect_to posts_path
    else
      flash.now[:danger] = "Could not create post."
      render 'new'
    end
  end

  def index
    @posts = Post.all
  end

  private

    def user_params
      params.require(:post).permit(:title, :body)
    end

    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in to make a new post."
        redirect_to root_url
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      log_in @user
      redirect_to root_url
    else
      flash[:danger] = "Credentials not valid."
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in (user)
    # log user into the session
    session[:user_id] = user.id
    # give user a new remember_token each login to prevent stale/stolen tokens
    user.create_remember_digest
    # store token in browser so when visiting pages, we know if they are signed in
    cookies.permanent[:remember_token] = user.remember_token
    @current_user = user
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif cookies.permanent[:remember_token]
      @current_user ||= User.find_by(remember_digest: User.digest(cookies.permanent[:remember_token]))
    else
      @current_user = nil
    end
  end

  def current_user=(user)
    @current_user = user
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    cookies.delete(:remember_token)
    session.delete(:user_id)
    @current_user.update_attribute(:remember_digest, nil)
    @current_user = nil
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_header.html.erb
<header class="navbar">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",            root_path %></li>
        <li><%= link_to "All Posts",       posts_path %></li>
        <li><%= link_to "Create New Post", new_post_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Log out", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_post.html.erb
<li>
  <h3><%= post.title %></h3>
  <% if logged_in? %>
    <p>Author: <%= post.user.name %></p>
  <% end %>

  <div class="post_body">
    <%= post.body %>
  </div>
</li>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/index.html.erb
<h1>All posts:</h1>

<ul class="posts">
  <%= render @posts %>
</ul>

app/views/posts/new.html.erb
<h1>New Post:</h1>

<%= form_for(@post, url: posts_path) do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :body %>
  <%= f.text_field :body %>

  <%= f.submit "Create post"%>
<% end %>

app/views/static_pages/index.html.erb
<h1>Welcome, Members!</h1>
<p>Non-members beware.</p>